### ISSUE TITLE
When can nopoll support openssl 1.1.1? the openssl 1.0.2 will be out of service the end of this year.

### ISSUE THREAD

**Issue by rock6958** [Comcast/nopoll#33]
When can nopoll support openssl 1.1.1? the openssl 1.0.2 will be out of service the end of this year. 
I think it will be security risk to continue to use the old version.

**Comment by shilpa24balaji** [comment]
@kraj any plan to upgrade to openssl 1.1.1?

**Comment by kraj** [comment]
OpenSSL 1.1.x is a major upgrade and we have achieved it in upcoming yocto 2.7 release as far as RDK is concerned we are upgrading to yocto 2.2 in 2019 and newer yocto is only going to happen in 2020 AFAICT

**Comment by shilpa24balaji** [comment]
@rock6958 ASPL nopoll supports openssl 1.1 since https://github.com/ASPLes/nopoll/releases/tag/0.4.5 release.
This comcast fork also pulls in 0.4.5
So nopoll can be used with higher version openssl but not in RDK
