### ISSUE TITLE
PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP should be avoided

### ISSUE THREAD

**Issue by armcc** [Comcast/nopoll#7]
PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP is not portable and using it prevents code from being built against musl libc.

The portable alternative is to use pthread_once() to run a small function which initialises the mutex and sets the type to PTHREAD_MUTEX_RECURSIVE at run time, before the mutex is first acquired.

For reference, see: https://build.opensuse.org/package/view_file/SUSE:SLE-12:GA/alsa-utils/0007-alsaloop-pcmjob.c-use-portable-way-to-initialize-rec.patch?expand=1

**Comment by schmidtw** [comment]
Good suggestion.  We'll look into applying a patch to be more portable.

**Comment by schmidtw** [comment]
I think this removes the PTHREAD_RECURSIVE_MUTEX_INITIALIZER_NP use.  Not sure if there is a way to do it that doesn't require a global static ... but the callback function with a void argument makes that quite difficult.
